version: '3.8'

services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - '9000:9000'
    volumes:
      - ../app:/var/www/app

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '8080:80'                    # Expor a porta 80 do container para a porta 8080 do host
    volumes:
      - ../app:/var/www/app
    depends_on:
      - php

