name: Build and Deploy
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip
          sudo pip3 install docker-compose

      - name: Build and Run Docker Compose
        run: |
          cd backend/
          docker-compose build
          docker-compose up -d

      - name: Wait for application to start
        run: sleep 30

      - name: Stop and remove Docker Compose containers
        run: cd backend/
        run: docker-compose down
