name: Build and Deploy
on:
  push:
    branches:
      - main 
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build NGINX
      run: cd backend/ && docker build . --file Dockerfile.nginx --tag pr4dox-nginx-app:$(date +%s) && cd .. 

    - name: Build PHP-FPH
      run: cd backend/ && docker build . --file Dockerfile.php --tag pr4dox-php-app:$(date +%s) && cd ..

    - name: Login to Docker Hub and push images
      env:
        DOCKER_CLI_AIO_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_CLI_AIO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
          cd backend/
          docker push pr4dox-nginx-app:$(date +%s) 
          docker push pr4dox-php-app:$(date +%s) 