name: Construir e Implantar
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar o código
        uses: actions/checkout@v2

      - name: Configurar o Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get -y install python3-pip
          sudo pip3 install docker-compose

      - name: Construir e Executar o Docker Compose
        run: |
          cd backend/
          docker-compose build
          docker-compose up -d

      - name: Aguardar a inicialização da aplicação
        run: sleep 30

      - name: Parar e remover os contêineres do Docker Compose
        run: |
          cd backend/
          docker-compose down

      - name: Login no Docker Hub e enviar imagem
        env:
          DOCKER_CLI_AIO_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_CLI_AIO_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          cd backend/
          docker-compose push

      - name: Enviar docker-compose.yml para o repositório do Docker Hub
        env:
          DOCKERHUB_REPO: pr4dox/pigz
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker tag app:latest $DOCKERHUB_REPO:latest
          docker push $DOCKERHUB_REPO:latest
          docker logout
